package com.fuzzybat23.HorseInfo;


import net.minecraft.client.Minecraft;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.SharedMonsterAttributes;
import net.minecraft.entity.passive.EntityHorse;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.text.translation.I18n;
import net.minecraftforge.client.event.RenderGameOverlayEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.text.DecimalFormat;

@net.minecraftforge.fml.common.Mod(modid = "horseinfo", version = "1.0", clientSideOnly = true, acceptedMinecraftVersions = "[1.12, 1.13]")
public class HorseInfo
{
    @net.minecraftforge.fml.common.Mod.Instance("HorseInfo")
    public static final String MODID = "horseinfo";

    @Mod.Instance
    public static HorseInfo instance;

    public static final Logger logger = LogManager.getLogger();


    @Mod.EventHandler
    @SideOnly(Side.CLIENT)
    public void preInit(FMLPreInitializationEvent event)
    {
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.version = "1.0";
        data.name = "Horse Info";
        data.description = "Displays horse info in debug screen.";
        data.authorList.add("Fuzzybat23");
        data.authorList.add("Lothrazar");
        data.url = "https://minecraft.curseforge.com/members/fuzzybat23/projects";
        data.credits = "Updated to 1.12, removed auto mount to keep it more vanilla.";
        data.logoFile = "assets/logo/logo.png";

        FMLCommonHandler.instance().bus().register(instance);
        MinecraftForge.EVENT_BUS.register(instance);
    }

    public static String lang(String name)
    {
        return I18n.translateToLocal(name);
    }

    @SideOnly(Side.CLIENT)
    @SubscribeEvent
    public void onRenderTextOverlay(RenderGameOverlayEvent.Text event)
    {
        Minecraft mc = Minecraft.getMinecraft();
        EntityPlayer player = mc.player;

        if(mc.gameSettings.showDebugInfo)
        {
            if(mc.objectMouseOver != null && mc.objectMouseOver.entityHit instanceof EntityHorse )
            {
                getHorseInfo(event, player, (EntityHorse)mc.objectMouseOver.entityHit);
            }
        }
    }

    @SideOnly(Side.CLIENT)
    private void getHorseInfo(RenderGameOverlayEvent.Text event, EntityPlayer player, EntityHorse horse)
    {
        //logger.info("horse.getHorseJumpStrength() = " + horse.getHorseJumpStrength() + " -> " + convertHorse(jump));

        DecimalFormat decimal = new DecimalFormat("0.00");

        event.getLeft().add("Horse Max HP:  " + getHorseMaxHP(horse));
        event.getLeft().add("Horse Speed:  " + decimal.format(getHorseMaxSpeed(horse)));
        event.getLeft().add("Horse Jump Height:  " + decimal.format(getHorseJumpHeight(horse)));
    }

    private static float getHorseJumpHeight(EntityHorse horse)
    {
        double yVelocity = horse.getHorseJumpStrength();
        double jumpHeight = 0;
        while (yVelocity > 0)
        {
            jumpHeight += yVelocity;
            yVelocity -= 0.08;
            yVelocity *= 0.98;
        }
        return (float)jumpHeight;
    }

    private static float getHorseMaxSpeed(EntityLivingBase entity)
    {
        return (float)entity.getEntityAttribute(SharedMonsterAttributes.MOVEMENT_SPEED).getAttributeValue() * 43;
    }

    public static int getHorseMaxHP(EntityLivingBase entity)
    {
        return (int) entity.getEntityAttribute(SharedMonsterAttributes.MAX_HEALTH).getAttributeValue();
    }
}
